services:
  - type: keyvalue
    name: real-estate-redis
    plan: free
    region: frankfurt
    maxmemoryPolicy: noeviction
    ipAllowList: []

  - type: web
    name: real-estate-api
    runtime: node
    plan: free
    region: frankfurt

    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production

      - key: NODE_VERSION
        value: "24.14.1"

      - key: REDIS_URL
        fromService:
          name: real-estate-redis
          type: keyvalue
          property: connectionString

      - key: MONGO_URI
        sync: false

      - key: JWT_SECRET
        sync: false

      - key: REFRESH_TOKEN_SECRET
        sync: false

      - key: CLIENT_URL
        sync: false

      - key: COOKIE_SAME_SITE
        value: "none"

      - key: JWT_ACCESS_EXPIRES_IN
        value: "15m"

      - key: JWT_REFRESH_EXPIRES_IN
        value: "7d"

      - key: CLOUDINARY_CLOUD_NAME
        sync: false

      - key: CLOUDINARY_API_KEY
        sync: false

      - key: CLOUDINARY_API_SECRET
        sync: false

      - key: RESEND_API_KEY
        sync: false

      - key: EMAIL_FROM
        sync: false

      - key: EMAIL_REPLY_TO
        sync: false

      - key: PASSWORD_RESET_URL
        sync: false

      - key: REUPLOAD_TIMEOUT_HOURS
        value: "24"

      - key: PENDING_BOOKING_TIMEOUT_HOURS
        value: "48"

      - key: PAYMENT_TIMEOUT_HOURS
        value: "24"
